### Update car data
POST http://localhost:8080/api/v1/car/update/data
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "4cfd9c1e-1922-4bde-bc5e-803ca858c397",
  "brand": "Lotus",
  "model": "Omega",
  "yearOfProduction": 2000,
  "power": 423,
  "torque": 500,
  "engineSize": 3.2,
  "averageFuelConsumption": 12.5,
  "minRankOfUser": 6.5,
  "pricePerDay": 230
}