### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email":  "adam@kowalski.pl",
  "password": "Qwerty123"
}

> {% client.global.set("auth-token", response.body.access_token);  %}