### Send email
POST http://localhost:8080/api/v1/auth/forgot-password/email
Content-Type: application/json

{
  "email": "jan@nowak.pl"
}

### Set new password
POST http://localhost:8080/api/v1/auth/forgot-password/set-new
Content-Type: application/json

{
  "email": "jan@nowak.pl",
  "token": "b69f1365-19d9-4dc4-87f2-74138ecd153c",
  "password": "QwertyQwerty123!"
}