### Get user by admin
GET http://localhost:8080/api/v1/user/get/id?id=8223dc2d-441d-4886-9512-997d6cc2b163
Authorization: Bearer {{auth-token}}

### Get user by user
GET http://localhost:8080/api/v1/user/get
Authorization: Bearer {{auth-token}}