### Lock user account
POST http://localhost:8080/api/v1/user/lock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "lockType": "TEMPORARY",
  "expirationDate": "2024-04-04",
  "reason": "OTHER",
  "userid": "5773c2c7-e62a-4699-9677-82efb1f15704"
}