### Lock user account
POST http://localhost:8080/api/v1/user/lock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "lockType": "TEMPORARY",
  "expirationDate": "2028-12-04",
  "reason": "OTHER",
  "userid": "8223dc2d-441d-4886-9512-997d6cc2b163"
}

### Unlock user account
POST http://localhost:8080/api/v1/user/unlock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "userid": "caebf99b-1aef-42fa-b110-736c8c73dcf9"
}