### Lock user account
POST http://localhost:8080/api/v1/user/lock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "lockType": "TEMPORARY",
  "expirationDate": "2024-04-04",
  "reason": "OTHER",
  "userid": "31767b0e-c4c6-4e92-a317-3928717293c3"
}