### Get specified car
GET  http://localhost:8080/api/v1/car/get?id=93570df3-9f6a-4826-aac1-26f704c4913a
Authorization: Bearer {{auth-token}}

### Get simplified list of all cars
GET http://localhost:8080/api/v1/car/get/simple/all

### Get simplified list of all available cars
GET  http://localhost:8080/api/v1/car/get/simple/available
Authorization: Bearer {{auth-token}}

### Get full list of all cars
GET  http://localhost:8080/api/v1/car/get/full/all
Authorization: Bearer {{auth-token}}

### Get full list of all available cars
GET  http://localhost:8080/api/v1/car/get/full/available
Authorization: Bearer {{auth-token}}
