### Get specified car
GET  http://localhost:8080/api/v1/car/get/99a4883d-3c28-4e29-bc79-0f84f18e5b4d
Authorization: Bearer {{auth-token}}

### Get simplified list of all cars
GET http://localhost:8080/api/v1/car/get/simple/all

### Get simplified list of all available cars
GET  http://localhost:8080/api/v1/car/get/simple/available
Authorization: Bearer {{auth-token}}

### Get full list of all cars
GET  http://localhost:8080/api/v1/car/get/full/all
Authorization: Bearer {{auth-token}}

### Get full list of all available cars
GET  http://localhost:8080/api/v1/car/get/full/available
Authorization: Bearer {{auth-token}}
