### Temporary lock car
POST http://localhost:8080/api/v1/car/lock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "99c5819c-f41d-4e49-bf7a-762c945aed87",
  "reason": "OTHER",
  "lockedTo": "2024-04-04"
}

### Unlock car
POST http://localhost:8080/api/v1/car/unlock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "99c5819c-f41d-4e49-bf7a-762c945aed87"
}

