### Temporary lock car
POST http://localhost:8080/api/v1/car/lock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "f2129185-53a0-4006-80c0-7161c9380825",
  "reason": "OTHER",
  "lockedTo": "2024-04-04"
}

### Unlock car
POST http://localhost:8080/api/v1/car/unlock
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "f2129185-53a0-4006-80c0-7161c9380825"
}

