### Rent car
POST http://localhost:8080/api/v1/car/rent/request
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "3444f120-b1d0-4399-add8-3dd6dc76e1e8",
  "rentedFrom": "2024-04-04",
  "rentedTo": "2024-04-14"
}

### Collect rented car
POST http://localhost:8080/api/v1/car/rent/collect
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carRentId": "83252aae-6708-48d0-afbd-4c42379fb617"
}

### Return rented car
POST http://localhost:8080/api/v1/car/rent/return
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carRentId": "83252aae-6708-48d0-afbd-4c42379fb617",
  "kilometersTraveled": 443.45
}