### Update car data
POST http://localhost:8080/api/v1/car/update/data
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "090574b0-a935-47dd-82fe-74e701c881c2",
  "brand": "Lotus",
  "model": "Omega",
  "yearOfProduction": 2000,
  "power": 423,
  "torque": 500,
  "engineSize": 3.2,
  "averageFuelConsumption": 12.5,
  "minRankOfUser": 6.5,
  "pricePerDay": 230
}