### Update car data
POST http://localhost:8080/api/v1/car/update/data
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "506defb4-ccd6-4b6d-a71d-6a5a91b404a9",
  "brand": "Lotus",
  "model": "Omega",
  "yearOfProduction": 2000,
  "power": 423,
  "torque": 500,
  "engineSize": 3.2,
  "averageFuelConsumption": 12.5,
  "minRankOfUser": 6.5,
  "pricePerDay": 230
}

### Update mileage
POST http://localhost:8080/api/v1/car/update/mileage
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "506defb4-ccd6-4b6d-a71d-6a5a91b404a9",
  "mileageToAdd": 500.7
}