### Update mileage
POST http://localhost:8080/api/v1/car/update/mileage
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "carId": "1bc28b46-7837-4d7c-bb4a-e110698c34d3",
  "mileageToAdd": 500.7
}