### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Ali",
  "lastName": "Bouali",
  "email":  "alibou@21mail.com",
  "password": "pa23234!Dord",
  "dateOfBirth": "2000-03-04"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Send email verifying token again
POST http://localhost:8080/api/v1/auth/register/verify/send-again
Content-Type: application/json

{
  "email": "alibou@21mail.com",
  "userId": ""
}