### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Aqwe",
  "lastName": "Boua",
  "email":  "alibou@21mail.com",
  "password": "pa13123123@Q",
  "dateOfBirth": "2006-03-18"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Send email verifying token again
POST http://localhost:8080/api/v1/auth/register/verify/send-again
Content-Type: application/json

{
  "email": "alibou@21mail.com",
  "userId": "f7be445d-83be-49c5-af33-aa236f9a1ab4"
}