### Register User
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstName": "Aqqweq",
  "lastName": "Bodas",
  "email":  "alibou@21mail.com",
  "password": "pa12!Qsdfdfsdf",
  "dateOfBirth": "2006-03-18"
}

> {% client.global.set("auth-token", response.body.access_token);  %}

### Send email verifying token again
POST http://localhost:8080/api/v1/auth/register/verify/send-again
Content-Type: application/json

{
  "email": "alibou@21mail.com",
  "userId": "0c8ee7ad-65e2-435a-a191-d88edcb77635"
}